### ISSUE TITLE
单词过长的话 样式出现重叠的问题

### ISSUE THREAD

**Issue by cuixiaorui** [cuixiaorui/earthworm#24]
<img width="1740" alt="image" src="https://github.com/cuixiaorui/earthworm/assets/12064746/b106c737-fd0c-4eac-8a1f-8fb0a6a5d49e">

这个问题是设计问题 是把单词大小缩小呢？ 还是如何设计？

**Comment by Lonely-shang** [comment]
![image](https://github.com/cuixiaorui/earthworm/assets/34124930/5f379e66-bf60-4782-8963-e570fc6c21c3)
我觉得可以把width:10vw;  改成 min-width: 5vw;  字体相应的调整小一点
