### ISSUE TITLE
存在歧义性和提示缺失

### ISSUE THREAD

**Issue by Jiuye-neko** [cuixiaorui/earthworm#29]
- 同一个中文翻译成英文可能存在多种写法，推荐将音标提示或者发音提示提前，不然会一直猜到正确答案出现 ;-)
    - `the` 的指向性比较模糊，单句中的 `这个` 比较容易想到 `this` 而不是 `the`，比较需要音标辅助
- 建议添加提示：
    - 大小写输入敏感
    - 使用空格切换输入单元格

**Comment by cuixiaorui** [comment]
大小写输入敏感已经添加
歧义性是通过播放句子的声音来解决的
按下 control 就可以播放声音
<img width="1352" alt="image" src="https://github.com/cuixiaorui/earthworm/assets/12064746/cef49578-6913-4578-b6a4-3f51919bee73">
