### ISSUE TITLE
Logo link

### ISSUE THREAD

**Issue by zhenyuWang** [cuixiaorui/earthworm#34]
At [https://earthworm-six.vercel.app](https://earthworm-six.vercel.app) address, when I click on the top logo, it will jump to [https://earthworm-six.vercel.app/main ](https://earthworm-six.vercel.app/main ) address and get a 404 page, so the function is not implemented or the link is wrong?

**Comment by cuixiaorui** [comment]
Yes this is a bug
welcome PR :)
