### ISSUE TITLE
通过快捷键来播放单词的声音

### ISSUE THREAD

**Issue by cuixiaorui** [cuixiaorui/earthworm#41]
通过快捷键来播放单词的声音
<img width="603" alt="image" src="https://github.com/cuixiaorui/earthworm/assets/12064746/bfbacfab-3d2e-4af8-86dd-bacf9a949c9d">
相当于点击声音按钮

但是用鼠标点击不符合我们“键盘侠”的风格
必须得要快捷键来播放 ：）

快捷键暂时没想到用什么

大家有什么好的主意

**Comment by zhenyuWang** [comment]
空格怎么样？

**Comment by cuixiaorui** [comment]
空格不错 好主意
