### ISSUE TITLE
通过空格播放单词的声音

### ISSUE THREAD

**Issue by cuixiaorui** [cuixiaorui/earthworm#46]
## what
用户希望可以在 question 页面也可以通过空格来播放句子的声音

<img width="1538" alt="image" src="https://github.com/cuixiaorui/earthworm/assets/12064746/85d1d9d0-b7ca-44fe-906e-009ef4702b65">

也就是这个页面  按下空格播放声音

## 现状
现在的逻辑是可以在 answer 页面通过空格来播放声音的

<img width="1520" alt="image" src="https://github.com/cuixiaorui/earthworm/assets/12064746/32bac543-19ef-4978-ac1a-bb059c1be10d">

## why
那么在 question 页面可以播放声音的好处可以解决**歧义性** 
比如 显示了一个中文 “不”， 那么答案有可能是 "no" 也有可能是 "don't "

那么这就产生的歧义   ，这时候如果可以让用户听到答案的英文声音 那么就可以解决这个歧义了

**Comment by HenryTSZ** [comment]
我来尝试一下

**Comment by HenryTSZ** [comment]
使用空格是不是需要讨论一下
因为在 question 页面 "空格" 还有一个作用是分隔输入的单词

改成使用 "alt/opt" 是不是也可以?
